webhook:
  secret: 'dXMLYnDkuTNPxUkFaPQUCPQtdymUFDJfniRIrOGpvpJ'
  port: 6000

gitlab:
  access_token: 'glpat-j8xsvBpWC_jJ7GaL2R-h'
  api_url: 'http://127.0.0.1:8200'

dify:
  api_key: 'app-1HTsxnKAIvSP70c1GKVJhweW'
  api_url: 'http://110.40.167.8:8088/v1/chat-messages'

deepseek:
  base_url: 'https://api.deepseek.com'
  token: 'sk-eb64ca97ec8248418ccbe309d23dee12'
  model: "deepseek-chat"

silicon_flow:
  base_url: 'https://api.siliconflow.cn'
  token: 'sk-jzbbqfdbnigbqofyuukrwlwaflogixndnjjvsdtljaxwedvt'
  model: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"

paths:
  input_dir: 'in'
  output_dir: 'out'